name: Docker Image CI

env:
  DOCKER_REGISTRY: ramkannans.jfrog.io
  APP_NAME: slipway-docker-dev-local/slipway-hello-world
  JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
  JF_CLI_VERSION: 2.11.0
  JFROG_CLI_BUILD_NAME: training
  JFROG_CLI_BUILD_NUMBER: 2.0.${{ github.run_id }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v2.0.0  
      with:
        version: ${{ env.JF_CLI_VERSION }}
    
    - name: Docker Login
      run: docker login -u "ramkannan2612@gmail.com" -p "$JFROG_PASSWORD" $DOCKER_REGISTRY

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "$DOCKER_REGISTRY/$APP_NAME:2.0.${{ github.run_id }}"

    - name: Push to JFrog
      run: docker push "$DOCKER_REGISTRY/$APP_NAME:2.0.${{ github.run_id }}"
      
    - name: Setup Server
      run: jfrog c add ramkannans --url="$DOCKER_REGISTRY" --user="ramkannan2612@gmail.com" --password="$JFROG_PASSWORD" ; jf c use ramkannans
      
    - name: Publish Docker Build Info
      run: |
        jfrog rt bce "$JFROG_CLI_BUILD_NAME" 2
        jfrog rt bag "$JFROG_CLI_BUILD_NAME" 2
        jfrog rt bp "$JFROG_CLI_BUILD_NAME" 2
