name: Docker CI Training Sample

env:
  DOCKER_REGISTRY: mainjpd.devops-acc-us.jfrog.team
  APP_NAME: demo-docker-virtual/slipway-hello-world
  JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
  JFROG_DATA_PASSWORD: ${{ secrets.JFROG_DATA_PASSWORD }}
  JF_CLI_VERSION: 2.53.1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v2.0.0  
      with:
        version: ${{ env.JF_CLI_VERSION }}
    
    - name: Docker Login
      run: docker login -u "admin" -p "$JFROG_PASSWORD" $DOCKER_REGISTRY

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "$DOCKER_REGISTRY/$APP_NAME:2.0.${{ github.run_id }}"

    - name: Push to JFrog
      run: docker push "$DOCKER_REGISTRY/$APP_NAME:2.0.${{ github.run_id }}"

    - name: Setup Server
      run: jfrog c add ramkannans --url="https://mainjpd.devops-acc-us.jfrog.team/" --user="admin" --password="$JFROG_DATA_PASSWORD" ; jfrog c show
      
    - name: Publish Docker Build Info
      run: |
        jfrog rt bce "$JFROG_CLI_BUILD_NAME" "$JFROG_CLI_BUILD_NUMBER"
        jfrog rt bag "$JFROG_CLI_BUILD_NAME" "$JFROG_CLI_BUILD_NUMBER"
        jfrog rt bp "$JFROG_CLI_BUILD_NAME" "$JFROG_CLI_BUILD_NUMBER"
